<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Observer;

class ActionPredispatchCheckoutOnepageSuccess implements \Magento\Framework\Event\ObserverInterface
{
    /**
     * @var \Az2009\Cielo\Helper\Data
     */
    protected $helper;

    /**
     * @var \Magento\Framework\Registry
     */
    protected $registry;

    /**
     * @var \Magento\Checkout\Model\Session
     */
    protected $checkoutSession;

    public function __construct(
        \Az2009\Cielo\Helper\Data $helper,
        \Magento\Checkout\Model\Session $checkoutSession,
        \Magento\Framework\Registry $registry
    ) {
        $this->checkoutSession = $checkoutSession;
        $this->registry = $registry;
        $this->helper = $helper;
    }

    public function execute(\Magento\Framework\Event\Observer $observe)
    {
        $request = $observe->getEvent()->getRequest();

        $order = $this->checkoutSession->getLastRealOrder();

        if (!$this->registry->registry('current_order')) {
            $this->registry->register('current_order', $order);
            $request->setParam('order_id', $order->getEntityId());
        }
    }
}