<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Helper;

class BankSlip extends Data
{
    /**
     * Get additional days for the ticket to expire
     */
    public function getAdditionalDays()
    {
        $config = $this->scopeConfig->getValue(
            'payment/az2009_cielo_bank_slip/additional_days',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );

        $config = intval($config);
        $config = "P{$config}D";

        return $config;
    }

    /**
     * Demonstration Text.
     *
     * @return mixed
     */
    public function getDemonstrative()
    {
        $config = $this->scopeConfig->getValue(
            'payment/az2009_cielo_bank_slip/demonstrative',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );

        return $config;
    }

    /**
     * Name of the Seller.
     *
     * @return mixed
     */
    public function getAssignor()
    {
        $config = $this->scopeConfig->getValue(
            'payment/az2009_cielo_bank_slip/assignor',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );

        return $config;
    }

    /**
     * Ticket number sent by the shopkeeper.
     * Used to count tickets issued ("OurNumber").
     */
    public function getBoletoNumber()
    {
        $config = $this->scopeConfig->getValue(
            'payment/az2009_cielo_bank_slip/boleto_number',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );

        return $config;
    }

    /**
     * Get Assignor Address
     *
     * @return mixed
     */
    public function getAssignorAddress()
    {
        $config = $this->scopeConfig->getValue(
            'payment/az2009_cielo_bank_slip/assignor_address',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );

        return $config;
    }

    /**
     * Get Assignor Address
     *
     * @return mixed
     */
    public function getAssignorIdentification()
    {
        $config = $this->scopeConfig->getValue(
            'payment/az2009_cielo_bank_slip/assignor_identification',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );

        return $config;
    }

    /**
     * Get provider Bradesco2 | BancoDoBrasil2
     *
     * @return mixed
     */
    public function getProvider()
    {
        $config = $this->scopeConfig->getValue(
            'payment/az2009_cielo_bank_slip/provider',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );

        return $config;
    }
}