<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Block\Adminhtml\Form\Field;

class Installment
    extends \Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray
{

    protected function _prepareToRender()
    {
        $this->addColumn('installment_boundary', [
            'label' => __('Amount (incl.)'),
            'style' => 'width:100px',
        ]);

        $this->addColumn('installment_frequency', [
            'label' => __('Maximum Number of Installments'),
            'style' => 'width:100px',
        ]);

        $this->_addAfter = false;
        $this->_addButtonLabel = __('Add Installment Boundary');
    }
}
