<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Block\Info;

class AbstractInfo extends \Magento\Payment\Block\Info\Cc
{
    /**
     * @var \Az2009\Cielo\Helper\Data
     */
    public $helper;

    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Az2009\Cielo\Helper\Data $helper,
        \Magento\Payment\Model\Config $paymentConfig, array $data = []
    ) {
        $this->helper = $helper;
        parent::__construct($context, $paymentConfig, $data);
    }

    /**
     * Define to show info payment only in admin
     *
     * @return bool
     */
    public function onlyShowAdmin()
    {
        if ($this->_appState->getAreaCode()
            == \Magento\Framework\App\Area::AREA_ADMINHTML
        ) {
            return true;
        }

        return false;
    }
}