<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Controller\Process;

class Payment extends \Az2009\Cielo\Controller\Postback\Index
{
    /**
     * @return \Magento\Framework\App\ResponseInterface
     */
    public function execute()
    {
        $url = '/';
        if ($this->_isValid()) {
            try {

                $postback = $this->helper->getPostbackByTransId($this->_paymentId);
                if (!($postback instanceof \Az2009\Cielo\Model\Method\AbstractMethod)) {
                    throw new \Exception((string)__('Order Not Found to PaymentId %1', $this->_paymentId));
                }

                $postback->setPaymentId($this->_paymentId)
                         ->process();

                if ($this->registry->registry('payment_captured')) {
                    return $this->_redirect('checkout/onepage/success');
                }

            } catch(\Az2009\Cielo\Exception\Cc $e) {
                $this->messageManager->addError($e->getMessage());
            } catch(\Exception $e) {
                $this->logger->info($e->getMessage());
                $this->messageManager->addError(__('Occurred an error during payment process. Contact the store.'));
            }

            $url = 'checkout/onepage/failure';

        }

        return $this->_redirect($url);
    }

    /**
     * @return bool
     */
    protected function _isValid()
    {
        $request = $this->getRequest();

        if(!$request->isPost()
            || !($this->_paymentId = $request->getParam('PaymentId'))
        ) {
            return false;
        }

        return true;
    }

}