<?php

namespace Az2009\Cielo\Block\Adminhtml\Cc;

class Data extends \Magento\Payment\Block\Form
{

    /**
     * @var \Magento\Backend\Model\Session\Quote
     */
    protected $sessionQuote;

    /**
     * @var \Magento\Framework\App\State
     */
    protected $state;

    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Model\Session\Quote $sessionQuote,
        \Magento\Framework\App\State $state,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->sessionQuote = $sessionQuote;
        $this->state = $state;
    }

    protected function _prepareLayout()
    {
        $payment = $this->getRequest()->getParam('payment');
        $order = $this->getRequest()->getParam('order');

        if ((isset($order['payment_method']) || isset($payment['method']))
            && ($order['payment_method'] == \Az2009\Cielo\Model\Method\Cc\Cc::CODE_PAYMENT
                    || $payment['method'] == \Az2009\Cielo\Model\Method\Cc\Cc::CODE_PAYMENT)
        ) {
            $this->setDataToSessionQuote($payment);
        }

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function setDataToSessionQuote(Array $data)
    {
        if ($this->state->getAreaCode()
            == \Magento\Framework\App\Area::AREA_ADMINHTML
        ) {
            if (isset($data['cc_number']) && !empty($data['cc_number'])) {
                $this->sessionQuote->setCcNumber($data['cc_number']);
            }

            if (isset($data['cc_name']) && !empty($data['cc_name'])) {
                $this->sessionQuote->setCcName($data['cc_name']);
            }

            if (isset($data['cc_type']) && !empty($data['cc_type'])) {
                $this->sessionQuote->setCcType($data['cc_type']);
            }

            if (isset($data['cc_exp_month']) && !empty($data['cc_exp_month'])) {
                $this->sessionQuote->setCcExpMonth($data['cc_exp_month']);
            }

            if (isset($data['cc_exp_year']) && !empty($data['cc_exp_year'])) {
                $this->sessionQuote->setCcExpYear($data['cc_exp_year']);
            }

            if (isset($data['cc_cid']) && !empty($data['cc_cid'])) {
                $this->sessionQuote->setCcCid($data['cc_cid']);
            }
        }
    }
}