<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Block\Order;

class Info extends \Magento\Sales\Block\Order\Info
{
    /**
     * @return bool
     */
    public function isShowBankSlip()
    {
        $payment = $this->getPayment();

        if ($payment->getMethod()
            !== \Az2009\Cielo\Model\Method\BankSlip\BankSlip::CODE_PAYMENT
        ) {
            return false;
        }

        return true;
    }

    /**
     * @return string
     */
    public function getLinkBankSlip()
    {
        $link = '';
        $payment = $this->getPayment();
        $data = $payment->getAdditionalInformation('payment_data');
        $data = \Zend\Json\Json::decode($data, true);

        if (empty($data) || !isset($data['Url'])) {
            return $link;
        }

        $link = $data['Url'];
        return $link;
    }

    /**
     * @return \Magento\Framework\DataObject|\Magento\Sales\Api\Data\OrderPaymentInterface|mixed|null
     */
    public function getPayment()
    {
        $order = $this->getOrder();
        $payment = $order->getPayment();
        return $payment;
    }
}