<div id="cieloccform" data-bind="scope:'cielo_cc_form'" data-mage-init='
    {
        "Magento_Ui/js/core/app": {
            "components": {
                "cielo_cc_form": {
                    "component": "Az2009_Cielo/js/cc/cielo-cc-form",
                    "template": "Az2009_Cielo/payment/cc-form"
                }
            }
        }
    }
'>
<!-- ko template: getTemplate() --><!-- /ko -->
</div>