<?php
    $code = $block->escapeHtml($block->getMethodCode());
    $method = $block->getMethod();
    $controller = $block->escapeHtml($block->getRequest()->getControllerName());
    $ccType = $block->getInfoData('cc_type');
    $ccExpMonth = $block->getInfoData('cc_exp_month');
    $ccExpYear = $block->getInfoData('cc_exp_year');
?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>"
          style="display:none;">
    
</fieldset>