<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Model\Method\Dc\Request;

class Customer extends \Magento\Framework\DataObject
{

    /**
     * @var \Magento\Sales\Model\Order
     */
    protected $order;

    /**
     * @var \Az2009\Cielo\Helper\Dc
     */
    protected $helper;

    public function __construct(
        \Az2009\Cielo\Helper\Dc $helper,
        array $data = []
    ) {
        $this->helper = $helper;
        parent::__construct($data);
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        $this->order = $this->getOrder();
        $this->billingAddress = $this->order->getBillingAddress();

        $payment = $this->order
                        ->getPayment()
                        ->getMethodInstance();

        $info = $payment->getInfoInstance();

        $this->setInfo($info);
        $this->setPayment($payment);

        return $this->setData(
                        [
                            'Customer' => [
                                'Name' => $this->helper->prepareString($this->billingAddress->getFirstname(), 34, 0),
                            ]
                        ]
                    )->toArray();
    }

}