<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Block\Form;

class BankSlip extends \Magento\Payment\Block\Form
{
    /**
     * Get code of method payment
     *
     * @return string
     */
    public function getCode()
    {
        return \Az2009\Cielo\Model\Method\BankSlip\BankSlip::CODE_PAYMENT;
    }
}