<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Plugin\Sales\Model;

class Order
{

    /**
     * @var \Az2009\Cielo\Helper\Data
     */
    protected $helper;

    public function __construct(\Az2009\Cielo\Helper\Data $helper)
    {
        $this->helper = $helper;
    }

    /**
     * @param \Magento\Sales\Model\Order $subject
     * @param $label
     * @return \Magento\Framework\Phrase|string
     */
    public function afterGetStatusLabel(
        \Magento\Sales\Model\Order $subject,
        $label
    )
    {
        if (in_array(
                $subject->getPayment()->getMethod(),
                $this->helper->getCodesPayment()
        ) && $subject->isPaymentReview()) {
            
            if (!($subject->getConfig() instanceof \Magento\Sales\Model\Order)) {
                return $label;
            }
            
            return $subject->getConfig()->getStateLabelByStateAndStatus(
                $subject->getState(),
                $subject->getStatus()
            );
        }

        return $label;
    }
}