<?php
/**
 * Jefferson Porto
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Az2009
 * @package   Az2009_Cielo
 *
 * @copyright Copyright (c) 2018 Jefferson Porto - (https://www.linkedin.com/in/jeffersonbatistaporto/)
 *
 * @author    Jefferson Porto <jefferson.b.porto@gmail.com>
 */
namespace Az2009\Cielo\Model\Method;

use Magento\Framework\DataObject;

abstract class Validate extends DataObject
{

    /**
     * @var array
     */
    protected $_fieldsValidate = [];

    /**
     * Get instance payment
     *
     * @return \Magento\Sales\Model\Order\Payment
     *
     * @throws \Az2009\Cielo\Exception\Cc
     */
    public function getPayment()
    {
        $payment = $this->getData('payment');
        if (!($payment instanceof \Az2009\Cielo\Model\Method\AbstractMethod)) {
            throw new \Az2009\Cielo\Exception\Cc(
                __('Occurred an error during payment process. Try Again.')
            );
        }

        return $payment;
    }

    /**
     * Get request before send
     *
     * @return mixed
     */
    public function getRequest()
    {
        $params = $this->getPayment()->getParams();
        $params = json_decode($params, true);
        return $params;
    }

    /**
     * Validate fields required
     *
     * @param $key
     * @param $value
     *
     * @throws \Az2009\Cielo\Exception\Cc
     */
    public function required($key, $value, $prefix = '')
    {
        if (isset($this->_fieldsValidate[$key])
            && $this->_fieldsValidate[$key]['required'] === true
            && empty($value)
        ) {
            throw new \Az2009\Cielo\Exception\Cc(__('%1 Field %2 required', $prefix, $key));
        }
    }

    /**
     * Validate length of the fields
     *
     * @param $key
     * @param $value
     *
     * @throws \Az2009\Cielo\Exception\Cc
     */
    public function maxLength($key, $value, $prefix = '')
    {
        if (isset($this->_fieldsValidate[$key]['maxlength'])
            && strlen($value) > $this->_fieldsValidate[$key]['maxlength']
        ) {
            throw new \Az2009\Cielo\Exception\Cc(
                __(
                    '%1 Field %2 exceed limit of %3 characters',
                    $prefix,
                    $key,
                    $this->_fieldsValidate[$key]['maxlength']
                )
            );
        }
    }

    /**
     * Todo validation
     */
    public abstract function validate();

}